// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService gère la persistance par opérateur de la configuration.
 * Chaque opérateur (onglet) possède sa propre Config, persistée dans son entrée OperatorService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as smsc$0 from "../smsc/models.js";

/**
 * @param {string} operatorId
 * @param {smsc$0.AutoMessage} msg
 * @returns {$CancellablePromise<void>}
 */
export function AddAutoMessage(operatorId, msg) {
    return $Call.ByID(3266683395, operatorId, msg);
}

/**
 * @param {string} operatorId
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAutoMessage(operatorId, index) {
    return $Call.ByID(700376627, operatorId, index);
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<smsc$0.AutoMessage[]>}
 */
export function GetAutoMessages(operatorId) {
    return $Call.ByID(336056439, operatorId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<smsc$0.Config>}
 */
export function GetConfig(operatorId) {
    return $Call.ByID(3160922438, operatorId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<smsc$0.DeliveryErrorRate[]>}
 */
export function GetDeliveryErrorRates(operatorId) {
    return $Call.ByID(2627199541, operatorId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<smsc$0.MessageErrorRate[]>}
 */
export function GetMessageErrorRates(operatorId) {
    return $Call.ByID(1448788018, operatorId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<smsc$0.Config>}
 */
export function ResetConfig(operatorId) {
    return $Call.ByID(2800066265, operatorId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} operatorId
 * @param {smsc$0.AutoMessage[]} msgs
 * @returns {$CancellablePromise<void>}
 */
export function SaveAutoMessages(operatorId, msgs) {
    return $Call.ByID(2824548158, operatorId, msgs);
}

/**
 * @param {string} operatorId
 * @param {smsc$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(operatorId, cfg) {
    return $Call.ByID(427220523, operatorId, cfg);
}

/**
 * @param {string} operatorId
 * @param {smsc$0.DeliveryErrorRate[]} rates
 * @returns {$CancellablePromise<void>}
 */
export function SaveDeliveryErrorRates(operatorId, rates) {
    return $Call.ByID(1427018252, operatorId, rates);
}

/**
 * @param {string} operatorId
 * @param {smsc$0.MessageErrorRate[]} rates
 * @returns {$CancellablePromise<void>}
 */
export function SaveMessageErrorRates(operatorId, rates) {
    return $Call.ByID(2979001829, operatorId, rates);
}

// Private type creation functions
const $$createType0 = smsc$0.AutoMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = smsc$0.Config.createFrom;
const $$createType3 = smsc$0.DeliveryErrorRate.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = smsc$0.MessageErrorRate.createFrom;
const $$createType6 = $Create.Array($$createType5);
