// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as smsc$0 from "../smsc/models.js";

/**
 * Operator is the persisted operator configuration.
 */
export class Operator {
    /**
     * Creates a new Operator instance.
     * @param {Partial<Operator>} [$$source = {}] - The source object to create the Operator.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {smsc$0.Config}
             */
            this["config"] = (new smsc$0.Config());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Operator instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Operator}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField3_0($$parsedSource["config"]);
        }
        return new Operator(/** @type {Partial<Operator>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = smsc$0.Config.createFrom;
