// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OperatorService persists operator configs in a bbolt database.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteOperator(id) {
    return $Call.ByID(4066211433, id);
}

/**
 * GetOperator returns a single operator by id.
 * @param {string} id
 * @returns {$CancellablePromise<[$models.Operator, boolean]>}
 */
export function GetOperator(id) {
    return $Call.ByID(3913119058, id).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    }));
}

/**
 * @returns {$CancellablePromise<$models.Operator[]>}
 */
export function GetOperators() {
    return $Call.ByID(1287611123).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.Operator} op
 * @returns {$CancellablePromise<void>}
 */
export function SaveOperator(op) {
    return $Call.ByID(3699264611, op);
}

/**
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function SaveOrder(ids) {
    return $Call.ByID(3475665829, ids);
}

// Private type creation functions
const $$createType0 = $models.Operator.createFrom;
const $$createType1 = $Create.Array($$createType0);
