// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SmppService manages one SMPP server per operator.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as smsc$0 from "../smsc/models.js";

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<void>}
 */
export function ClearMessages(operatorId) {
    return $Call.ByID(203870199, operatorId);
}

/**
 * @param {string} operatorId
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DropSession(operatorId, id) {
    return $Call.ByID(4260111933, operatorId, id);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLocalIPs() {
    return $Call.ByID(1230596385).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} operatorId
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<smsc$0.MessageInfo[]>}
 */
export function GetMessages(operatorId, offset, limit) {
    return $Call.ByID(3904980438, operatorId, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<smsc$0.Config>}
 */
export function GetOperatorConfig(operatorId) {
    return $Call.ByID(2365857284, operatorId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<smsc$0.SessionInfo[]>}
 */
export function GetSessions(operatorId) {
    return $Call.ByID(2270231223, operatorId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<smsc$0.Stats>}
 */
export function GetStats(operatorId) {
    return $Call.ByID(3957192537, operatorId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRunning(operatorId) {
    return $Call.ByID(695776961, operatorId);
}

/**
 * @param {smsc$0.SendMessageRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(req) {
    return $Call.ByID(1438857139, req);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3655820093, app);
}

/**
 * @param {string} operatorId
 * @param {number} port
 * @param {string} ip
 * @returns {$CancellablePromise<void>}
 */
export function StartServer(operatorId, port, ip) {
    return $Call.ByID(2445603929, operatorId, port, ip);
}

/**
 * @param {string} operatorId
 * @returns {$CancellablePromise<void>}
 */
export function StopServer(operatorId) {
    return $Call.ByID(119159841, operatorId);
}

/**
 * UpdateOperatorConfig replaces the in-memory config for an operator and hot-applies
 * it to the running server (if any).
 * @param {string} operatorId
 * @param {smsc$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateOperatorConfig(operatorId, cfg) {
    return $Call.ByID(2275205333, operatorId, cfg);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = smsc$0.MessageInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = smsc$0.Config.createFrom;
const $$createType4 = smsc$0.SessionInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = smsc$0.Stats.createFrom;
