// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * AutoMessage is a template used for periodic auto-delivery to connected clients.
 */
export class AutoMessage {
    /**
     * Creates a new AutoMessage instance.
     * @param {Partial<AutoMessage>} [$$source = {}] - The source object to create the AutoMessage.
     */
    constructor($$source = {}) {
        if (!("fromAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromAddress"] = "";
        }
        if (!("fromTon" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromTon"] = 0;
        }
        if (!("fromNpi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromNpi"] = 0;
        }
        if (!("toAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toAddress"] = "";
        }
        if (!("toTon" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toTon"] = 0;
        }
        if (!("toNpi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toNpi"] = 0;
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("dataCoding" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dataCoding"] = 0;
        }
        if (!("hasUdh" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasUdh"] = false;
        }
        if (!("tlvs" in $$source)) {
            /**
             * @member
             * @type {TLV[]}
             */
            this["tlvs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AutoMessage}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tlvs" in $$parsedSource) {
            $$parsedSource["tlvs"] = $$createField9_0($$parsedSource["tlvs"]);
        }
        return new AutoMessage(/** @type {Partial<AutoMessage>} */($$parsedSource));
    }
}

/**
 * Config holds the full application configuration persisted to disk.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("bindIp" in $$source)) {
            /**
             * e.g. "0.0.0.0", "127.0.0.1"
             * @member
             * @type {string}
             */
            this["bindIp"] = "";
        }
        if (!("authRequired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["authRequired"] = false;
        }
        if (!("systemId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemId"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("pduTimeoutMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pduTimeoutMs"] = 0;
        }
        if (!("enquireIntervalMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["enquireIntervalMs"] = 0;
        }
        if (!("processingMinMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["processingMinMs"] = 0;
        }
        if (!("processingMaxMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["processingMaxMs"] = 0;
        }
        if (!("multipartMode" in $$source)) {
            /**
             * 0=UDH 1=UDH16 2=SAR-TLV 3=Payload-TLV
             * @member
             * @type {number}
             */
            this["multipartMode"] = 0;
        }
        if (!("deliverMode" in $$source)) {
            /**
             * 0=forward_sm 1=deliver_sm
             * @member
             * @type {number}
             */
            this["deliverMode"] = 0;
        }
        if (!("echo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["echo"] = false;
        }
        if (!("generatePerMinute" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generatePerMinute"] = 0;
        }
        if (!("randomOrder" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["randomOrder"] = false;
        }
        if (!("keepMessages" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keepMessages"] = 0;
        }
        if (!("serverLogEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["serverLogEnabled"] = false;
        }
        if (!("sessionLogEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sessionLogEnabled"] = false;
        }
        if (!("pduLogEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pduLogEnabled"] = false;
        }
        if (!("serverLogPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverLogPath"] = "";
        }
        if (!("sessionLogPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionLogPath"] = "";
        }
        if (!("messageErrorRates" in $$source)) {
            /**
             * @member
             * @type {MessageErrorRate[]}
             */
            this["messageErrorRates"] = [];
        }
        if (!("deliveryErrorRates" in $$source)) {
            /**
             * @member
             * @type {DeliveryErrorRate[]}
             */
            this["deliveryErrorRates"] = [];
        }
        if (!("autoMessages" in $$source)) {
            /**
             * @member
             * @type {AutoMessage[]}
             */
            this["autoMessages"] = [];
        }
        if (!("lastReference" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastReference"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField20_0 = $$createType3;
        const $$createField21_0 = $$createType5;
        const $$createField22_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messageErrorRates" in $$parsedSource) {
            $$parsedSource["messageErrorRates"] = $$createField20_0($$parsedSource["messageErrorRates"]);
        }
        if ("deliveryErrorRates" in $$parsedSource) {
            $$parsedSource["deliveryErrorRates"] = $$createField21_0($$parsedSource["deliveryErrorRates"]);
        }
        if ("autoMessages" in $$parsedSource) {
            $$parsedSource["autoMessages"] = $$createField22_0($$parsedSource["autoMessages"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * DeliveryErrorRate maps a delivery status text to a probability.
 */
export class DeliveryErrorRate {
    /**
     * Creates a new DeliveryErrorRate instance.
     * @param {Partial<DeliveryErrorRate>} [$$source = {}] - The source object to create the DeliveryErrorRate.
     */
    constructor($$source = {}) {
        if (!("statusText" in $$source)) {
            /**
             * DELIVRD, FAILED, EXPIRED, etc.
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("occurrence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["occurrence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeliveryErrorRate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeliveryErrorRate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeliveryErrorRate(/** @type {Partial<DeliveryErrorRate>} */($$parsedSource));
    }
}

/**
 * Direction of a message.
 * @readonly
 * @enum {string}
 */
export const Direction = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DirIn: "IN",
    DirOut: "OUT",
};

/**
 * MessageErrorRate maps an ESME status code to a probability (percentage 1-100).
 */
export class MessageErrorRate {
    /**
     * Creates a new MessageErrorRate instance.
     * @param {Partial<MessageErrorRate>} [$$source = {}] - The source object to create the MessageErrorRate.
     */
    constructor($$source = {}) {
        if (!("statusCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["statusCode"] = 0;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("occurrence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["occurrence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageErrorRate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageErrorRate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageErrorRate(/** @type {Partial<MessageErrorRate>} */($$parsedSource));
    }
}

/**
 * MessageInfo is the read-only snapshot of a processed message sent to the frontend.
 */
export class MessageInfo {
    /**
     * Creates a new MessageInfo instance.
     * @param {Partial<MessageInfo>} [$$source = {}] - The source object to create the MessageInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {Direction}
             */
            this["direction"] = Direction.$zero;
        }
        if (!("systemId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemId"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionId"] = 0;
        }
        if (!("fromAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromAddress"] = "";
        }
        if (!("fromTon" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromTon"] = 0;
        }
        if (!("fromNpi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromNpi"] = 0;
        }
        if (!("toAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toAddress"] = "";
        }
        if (!("toTon" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toTon"] = 0;
        }
        if (!("toNpi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toNpi"] = 0;
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("dataCoding" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dataCoding"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * PENDING, SENT, FAILED, DENIED
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("reference" in $$source)) {
            /**
             * message ID string
             * @member
             * @type {string}
             */
            this["reference"] = "";
        }
        if (!("isDeliveryReport" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDeliveryReport"] = false;
        }
        if (!("requestDlr" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requestDlr"] = false;
        }
        if (!("hasUdh" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasUdh"] = false;
        }
        if (!("sequenceNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sequenceNumber"] = 0;
        }
        if (!("commandStatus" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["commandStatus"] = 0;
        }
        if (!("tlvs" in $$source)) {
            /**
             * @member
             * @type {TLV[]}
             */
            this["tlvs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageInfo}
     */
    static createFrom($$source = {}) {
        const $$createField20_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tlvs" in $$parsedSource) {
            $$parsedSource["tlvs"] = $$createField20_0($$parsedSource["tlvs"]);
        }
        return new MessageInfo(/** @type {Partial<MessageInfo>} */($$parsedSource));
    }
}

/**
 * SendMessageRequest is the payload the frontend sends when manually injecting a deliver_sm.
 */
export class SendMessageRequest {
    /**
     * Creates a new SendMessageRequest instance.
     * @param {Partial<SendMessageRequest>} [$$source = {}] - The source object to create the SendMessageRequest.
     */
    constructor($$source = {}) {
        if (!("operatorId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operatorId"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionId"] = 0;
        }
        if (!("fromAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromAddress"] = "";
        }
        if (!("fromTon" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromTon"] = 0;
        }
        if (!("fromNpi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromNpi"] = 0;
        }
        if (!("toAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toAddress"] = "";
        }
        if (!("toTon" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toTon"] = 0;
        }
        if (!("toNpi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toNpi"] = 0;
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("dataCoding" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dataCoding"] = 0;
        }
        if (!("tlvs" in $$source)) {
            /**
             * @member
             * @type {TLV[]}
             */
            this["tlvs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendMessageRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendMessageRequest}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tlvs" in $$parsedSource) {
            $$parsedSource["tlvs"] = $$createField10_0($$parsedSource["tlvs"]);
        }
        return new SendMessageRequest(/** @type {Partial<SendMessageRequest>} */($$parsedSource));
    }
}

/**
 * SessionInfo is the read-only snapshot of a connected session sent to the frontend.
 */
export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("systemId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemId"] = "";
        }
        if (!("systemType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemType"] = "";
        }
        if (!("bindType" in $$source)) {
            /**
             * TX, RX, TRX
             * @member
             * @type {string}
             */
            this["bindType"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("addressRange" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["addressRange"] = "";
        }
        if (!("addressRangeTon" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["addressRangeTon"] = 0;
        }
        if (!("addressRangeNpi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["addressRangeNpi"] = 0;
        }
        if (!("state" in $$source)) {
            /**
             * BINDING, BOUND, CLOSED
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("connectedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectedAt"] = "";
        }
        if (!("msgIn" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["msgIn"] = 0;
        }
        if (!("msgOut" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["msgOut"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

/**
 * Stats is the live statistics snapshot streamed to the frontend.
 */
export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("serverRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["serverRunning"] = false;
        }
        if (!("sessionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionCount"] = 0;
        }
        if (!("totalReceived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalReceived"] = 0;
        }
        if (!("totalSent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSent"] = 0;
        }
        if (!("receivedPerSecond" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["receivedPerSecond"] = 0;
        }
        if (!("sentPerSecond" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sentPerSecond"] = 0;
        }
        if (!("lastReference" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastReference"] = 0;
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("sessions" in $$source)) {
            /**
             * @member
             * @type {SessionInfo[]}
             */
            this["sessions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField8_0($$parsedSource["sessions"]);
        }
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

/**
 * TLV is an application-level TLV descriptor (tag + typed value).
 */
export class TLV {
    /**
     * Creates a new TLV instance.
     * @param {Partial<TLV>} [$$source = {}] - The source object to create the TLV.
     */
    constructor($$source = {}) {
        if (!("tag" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tag"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * STRING, HEX, INT32, INT16, INT8
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("hexValue" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hexValue"] = "";
        }
        if (!("typedValue" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["typedValue"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TLV instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TLV}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TLV(/** @type {Partial<TLV>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = TLV.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = MessageErrorRate.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = DeliveryErrorRate.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = AutoMessage.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = SessionInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
